# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 关于我们
    url: '#hero'
    weight: 10
  - name: 成员
    url: '#member'
    weight: 20
  - name: 新闻&活动
    url: '#news'
    weight: 30
  # - name: Events
  #   url: '#events'
  #   weight: 40
  # - name: Talks
  #   url: '#talks'
  #   weight: 50
  # - name: Publications
  #   url: '#featured'
  #   weight: 60
  - name: Alumni
    url: '#alumni'
    weight: 70
  # - name: Courses
  #   url: courses/
  #   weight: 60
  - name: 联系我们
    url: '#contact'
    weight: 80
