---
title: Stanford Chinese Postdoc Journal Club and Oral Presentation Improvement
author: Xiaotao Shen
date: '2022-01-08'
slug: event
categories:
  - event
tags:
  - Blog
  - English
image:
  caption: ''
  focal_point: ''
output:
  blogdown::html_page:
    toc: true
    number_sections: true
---

# Journal Club Course

## Course Organizer

* Xin Zhou PhD

* Xiaotao Shen PhD

## Finiace Manger: 

* Chuchu Wang PhD

## Funding

This course is financially supported by SURPAS (the Stanford University Postdoctoral Association) and SCPA (Stanford Chinese Postdoctoral Association).

# Purpose of the course

This course aims to help bring cutting-edge interdisciplinary research topics related to biomedical sciences. We not only discuss the most recent advances in research publications but also help to improve the presentation skills of Non-native English-speaker. This presentation platform is also intended to promote collaborations between participants. The majority of the course participants are postdoctoral fellows from Stanford Medicine, with several external affiliated members.

# List of the presentatians by now

```{r, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE, message=FALSE}
data = readxl::read_xlsx("Schedule.xlsx")
library(knitr)
kable(data, format = "markdown")
```
---

# **关于SCPA**

斯坦福中国博士后协会(Stanford Chinese Postdoctoral Association, SCPA)是斯坦福所有中国(华人)博士后的组织.我们欢迎所有在斯坦福的中国/华人博士后加入到我们协会.我们的使命是促进中国/华人博士后的交流,学习,并为他们的学习,工作和生活提供力所能及的帮助.

非常欢迎大家跟我们联系,交流.

## 微信公众号
该微信公众号是SCPA的官方微信公众号,欢迎大家关注!

[Wechat offical account](https://www.shenxt.info/files/scpa_wechat.jpeg)

## SCPA官网
SCPA官方网站.
https://scpa.netlify.app/
点击阅读原文访问.

## SCPA官方微信群
欢迎加入SCPA博后访问学者微信群.
添加群主微信(shenxt1990).

[Wechat group](https://www.shenxt.info/files/wechat_QR.jpg)

## SCPA Stanford Email list
点击该链接[https://mailman.stanford.edu/mailman/listinfo/chinesepostdocs](https://mailman.stanford.edu/mailman/listinfo/chinesepostdocs).加入我们的email list.
